version: '3'
services:
  app:
    build: .
    ports:
      - "3008:3008"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis"
    ports:
      - "6379:6379"
